name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Build wheels
        uses: PyO3/maturin-action@v1
        with:
          command: build
          args: --release --out dist --find-interpreter
          sccache: 'true'
          manylinux: auto
      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}
          path: dist

  publish:
    name: Create Release
    runs-on: ubuntu-latest
    needs: build_wheels
    steps:
      - uses: actions/checkout@v4
      - name: Download all wheels
        uses: actions/download-artifact@v4
        with:
          path: dist
          pattern: wheels-*
          merge-multiple: true
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
          body: |
            Added indeterminate mode.
            Fixed some rust bugs and minload efficiency bugs.
          token: ${{ secrets.GITHUB_TOKEN }}
